n = (input('Digite algo:'))
print('O tipo primitivo desse valor é {}'.format ( type(n)))
print('É alfabetico: {}'.format(n.isalpha()))
print('Só tem espaços: {}'.format (n.isspace()))
print('É um numero: {}'.format(n.isnumeric()))
print('É alfanumerico: {}'.format(n.isalnum()))
print('Está em maiúscula: {}'.format(n.isupper()))
print('Está em minúscula: {}'.format(n.islower()))
print('É printável: {}'.format(n.isprintable()))
print('Está em capitalizada: {}'.format(n.istitle()))

