print('=' * 40)
print('Este é um gerador de tabuada') 
print('=' * 40)
n = float(input('Digite qual o número que voce quer ver a multiplicação de 0 a 10: '))
a = 0
b = 1
c = 2
d = 3
e = 4
f = 5
g = 6
h = 7
i = 8
j = 9
k = 10

print(' {} * {: } = {: .2f}'. format(n , a , n * a)) 
print(' {} * {: } = {: .2f}'. format(n , b , n * b))
print(' {} * {: } = {:2.2f}'. format(n , c , n * c)) 
print(' {} * {: } = {: .2f}'. format(n , d , n * d))
print(' {} * {: } = {: .2f}'. format(n , e , n * e))
print(' {} * {: } = {:2.2f}'. format(n , f , n * f))
print(' {} * {: } = {:2.2f}'. format(n , g , n * g))
print(' {} * {: } = {:2.2f}'. format(n , h , n * h))
print(' {} * {: } = {:2.2f}'. format(n , i , n * i))
print(' {} * {: } = {:2.2f}'. format(n , j , n * j))
print(' {} * {} = {:2.2f}'. format(n , k , n * k))
print('=' * 40)
print('=' * 40)
