print (' ')
print('=' * 40)
print('Este é um conversor e contador de caracteres') 
print('=' * 40)
frase = input('Digite seu nome: ').strip()
print (' ')
print('O seu nome em maiúsculas é: {}'.format(frase.upper()))
print('O seu nome em minúsculas é: {}'.format(frase.lower()))
print (' ')
print('=' * 40)
nnome = len(frase.replace(" ",""))
nomed = frase.split()
numdi = len(nomed[0])
print('O seu nome tem  {} letras e o seu primeiro nome tem {} letras'.format(nnome, numdi))
print (' ')
print('=' * 40)
print (' ')
print('Ou ...')
print('Seu nome tem ao todo {} letras '.format(len(frase) - frase.count(' ')))
print('Seu primeiro nome tem {} letras'.format(frase.find(' ')))